/*
    CONTRIBUTORS:
        Sean Pesce

*/

#pragma once

#ifndef SP_UTILITY_IO_VK_NAME_STRINGS_H_
#define SP_UTILITY_IO_VK_NAME_STRINGS_H_

#include "sp/sp.h"


__SP_NAMESPACE
namespace io {


// #define SP_DEFINE_VK_NAME_STRINGS_  // Must be defined to use Virtual-key code name strings (opt-in by default because it increases file size by a few KB)


#ifdef _WIN32


#ifdef SP_DEFINE_VK_NAME_STRINGS_
    /*
        Windows Virtual-key code strings

        Source:
        https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396
    */

    #define _SP_VK_NAME_INVALID_    "Invalid key code"
    #define _SP_VK_NAME_UNDEFINED_  "Undefined"
    #define _SP_VK_NAME_UNASSIGNED_ "Unassigned"
    #define _SP_VK_NAME_RESERVED_   "Reserved"

    #define _SP_VK_NUMPAD_PREFIX_    "Numpad "
    #define _SP_VK_NAME_KEY_SUFFIX_  " key"

    #define _SP_VK_NAME_SEPARATOR_INTERNATIONAL_ "Separator"
    #define _SP_VK_NAME_SEPARATOR_US_ "Decimal (Separator)"
    #define _SP_VK_NAME_SEPARATOR_DE_ "Comma (Separator)"
    #define _SP_VK_NAME_SEPARATOR__   _SP_VK_NAME_SEPARATOR_INTERNATIONAL_    // Some sources claim this is never actually generated by the keyboard

    // Microsoft documentation description:
    //    "Used to pass Unicode characters as if they were keystrokes. The VK_PACKET key is the low word of a 32-bit Virtual Key value used for non-keyboard input methods."
    #define _SP_VK_NAME_VK_PACKET_ "Unicode keystroke packet"    // 0xE7

    #define _SP_VK_NAME_VK_NONAME_MS_ "VK_NONAME"
    #define _SP_VK_NAME_VK_NONAME__   _SP_VK_NAME_RESERVED_    // 0xFC

    #define    _SP_VK_NAME_OEM_SPECIFIC_GENERIC_ "OEM specific"
    #define    _SP_VK_NAME_OEM_SPECIFIC_0x92_    _SP_VK_NAME_OEM_SPECIFIC_GENERIC_
    #define    _SP_VK_NAME_OEM_SPECIFIC_0x93_    _SP_VK_NAME_OEM_SPECIFIC_GENERIC_
    #define    _SP_VK_NAME_OEM_SPECIFIC_0x94_    _SP_VK_NAME_OEM_SPECIFIC_GENERIC_
    #define    _SP_VK_NAME_OEM_SPECIFIC_0x95_    _SP_VK_NAME_OEM_SPECIFIC_GENERIC_
    #define    _SP_VK_NAME_OEM_SPECIFIC_0x96_    _SP_VK_NAME_OEM_SPECIFIC_GENERIC_
    #define    _SP_VK_NAME_OEM_SPECIFIC_0xE1_    _SP_VK_NAME_OEM_SPECIFIC_GENERIC_
    #define    _SP_VK_NAME_OEM_SPECIFIC_0xE3_    _SP_VK_NAME_OEM_SPECIFIC_GENERIC_
    #define    _SP_VK_NAME_OEM_SPECIFIC_0xE4_    _SP_VK_NAME_OEM_SPECIFIC_GENERIC_
    #define    _SP_VK_NAME_OEM_SPECIFIC_0xE6_    _SP_VK_NAME_OEM_SPECIFIC_GENERIC_
    #define    _SP_VK_NAME_OEM_SPECIFIC_0xE9_    _SP_VK_NAME_OEM_SPECIFIC_GENERIC_
    #define    _SP_VK_NAME_OEM_SPECIFIC_0xEA_    _SP_VK_NAME_OEM_SPECIFIC_GENERIC_
    #define    _SP_VK_NAME_OEM_SPECIFIC_0xEB_    _SP_VK_NAME_OEM_SPECIFIC_GENERIC_
    #define    _SP_VK_NAME_OEM_SPECIFIC_0xEC_    _SP_VK_NAME_OEM_SPECIFIC_GENERIC_
    #define    _SP_VK_NAME_OEM_SPECIFIC_0xED_    _SP_VK_NAME_OEM_SPECIFIC_GENERIC_
    #define    _SP_VK_NAME_OEM_SPECIFIC_0xEE_    _SP_VK_NAME_OEM_SPECIFIC_GENERIC_
    #define    _SP_VK_NAME_OEM_SPECIFIC_0xEF_    _SP_VK_NAME_OEM_SPECIFIC_GENERIC_
    #define    _SP_VK_NAME_OEM_SPECIFIC_0xF0_    _SP_VK_NAME_OEM_SPECIFIC_GENERIC_
    #define    _SP_VK_NAME_OEM_SPECIFIC_0xF1_    _SP_VK_NAME_OEM_SPECIFIC_GENERIC_
    #define    _SP_VK_NAME_OEM_SPECIFIC_0xF2_    _SP_VK_NAME_OEM_SPECIFIC_GENERIC_
    #define    _SP_VK_NAME_OEM_SPECIFIC_0xF3_    _SP_VK_NAME_OEM_SPECIFIC_GENERIC_
    #define    _SP_VK_NAME_OEM_SPECIFIC_0xF4_    _SP_VK_NAME_OEM_SPECIFIC_GENERIC_
    #define    _SP_VK_NAME_OEM_SPECIFIC_0xF5_    _SP_VK_NAME_OEM_SPECIFIC_GENERIC_

    #define _SP_VK_NAME_OEM_1_GENERIC_ "OEM 1"
    #define _SP_VK_NAME_OEM_1_INTERNATIONAL_ "OEM 1 (';:' in US)"
    #define _SP_VK_NAME_OEM_1_US_ "Colon/semicolon"
    #define _SP_VK_NAME_OEM_1__ _SP_VK_NAME_OEM_1_INTERNATIONAL_

    #define _SP_VK_NAME_OEM_2_GENERIC_ "OEM 2"
    #define _SP_VK_NAME_OEM_2_INTERNATIONAL_ "OEM 2 ('/?' in US)"
    #define _SP_VK_NAME_OEM_2_US_ "Question mark/forward slash"
    #define _SP_VK_NAME_OEM_2__ _SP_VK_NAME_OEM_2_INTERNATIONAL_

    #define _SP_VK_NAME_OEM_3_GENERIC_ "OEM 3"
    #define _SP_VK_NAME_OEM_3_INTERNATIONAL_ "OEM 3 ('`~' in US)"
    #define _SP_VK_NAME_OEM_3_US_ "Tilde (~)"
    #define _SP_VK_NAME_OEM_3__ _SP_VK_NAME_OEM_3_INTERNATIONAL_

    #define _SP_VK_NAME_OEM_4_GENERIC_ "OEM 4"
    #define _SP_VK_NAME_OEM_4_INTERNATIONAL_ "OEM 4 ('[{' in US)"
    #define _SP_VK_NAME_OEM_4_US_ "Left bracket ([)"
    #define _SP_VK_NAME_OEM_4__ _SP_VK_NAME_OEM_4_INTERNATIONAL_

    #define _SP_VK_NAME_OEM_5_GENERIC_ "OEM 5"
    #define _SP_VK_NAME_OEM_5_INTERNATIONAL_ "OEM 5 ('\\|' in US)"
    #define _SP_VK_NAME_OEM_5_US_ "Backslash (\\)"
    #define _SP_VK_NAME_OEM_5__ _SP_VK_NAME_OEM_5_INTERNATIONAL_

    #define _SP_VK_NAME_OEM_6_GENERIC_ "OEM 6"
    #define _SP_VK_NAME_OEM_6_INTERNATIONAL_ "OEM 6 (']}' in US)"
    #define _SP_VK_NAME_OEM_6_US_ "Right bracket (])"
    #define _SP_VK_NAME_OEM_6__ _SP_VK_NAME_OEM_6_INTERNATIONAL_

    #define _SP_VK_NAME_OEM_7_GENERIC_ "OEM 7"
    #define _SP_VK_NAME_OEM_7_INTERNATIONAL_ "OEM 7 (Single/double quote in US)"
    #define _SP_VK_NAME_OEM_7_US_ "Single/double quote"
    #define _SP_VK_NAME_OEM_7__ _SP_VK_NAME_OEM_7_INTERNATIONAL_

    #define _SP_VK_NAME_OEM_8_GENERIC_ "OEM 8"
    #define _SP_VK_NAME_OEM_8__ _SP_VK_NAME_OEM_8_GENERIC_

    #define _SP_VK_NAME_OEM_102_GENERIC_ "OEM 102"
    #define _SP_VK_NAME_OEM_102_INTERNATIONAL_ "OEM 102 (Angle bracket/backslash on RT 102-key keyboard)"
    #define _SP_VK_NAME_OEM_102_RT_102_ "Angle bracket/backslash"
    #define _SP_VK_NAME_OEM_102__ _SP_VK_NAME_OEM_102_INTERNATIONAL_


    // Names of each keyboard/mouse button that corresponds to a virtual-key code
    const char *VK_NAME[256] =
    {
            _SP_VK_NAME_INVALID_,
            "Left mouse button",
            "Right mouse button",
            "Break",
            "Middle mouse button",
            "X1 mouse button",
            "X2 mouse button",
            _SP_VK_NAME_UNDEFINED_,
            "Backspace",
            "Tab",
            _SP_VK_NAME_RESERVED_,
            _SP_VK_NAME_RESERVED_,
            "Clear",
            "Enter",
            _SP_VK_NAME_UNDEFINED_,
            _SP_VK_NAME_UNDEFINED_,
            "Shift",
            "Ctrl",
            "Alt",
            "Pause",
            "Caps lock",
            "IME Kana/Hangul",
            _SP_VK_NAME_UNDEFINED_,
            "IME Junja",
            "IME final",
            "IME Hanja/Kanji",
            _SP_VK_NAME_UNDEFINED_,
            "Escape",
            "IME convert",
            "IME nonconvert",
            "IME accept",
            "IME mode change",
            "Spacebar",
            "Page up",
            "Page down",
            "End",
            "Home",
            "Left arrow",
            "Up arrow",
            "Right arrow",
            "Down arrow",
            "Select",
            "Print",
            "Execute",
            "Print screen",
            "Insert",
            "Delete",
            "Help",
            "0" _SP_VK_NAME_KEY_SUFFIX_,
            "1" _SP_VK_NAME_KEY_SUFFIX_,
            "2" _SP_VK_NAME_KEY_SUFFIX_,
            "3" _SP_VK_NAME_KEY_SUFFIX_,
            "4" _SP_VK_NAME_KEY_SUFFIX_,
            "5" _SP_VK_NAME_KEY_SUFFIX_,
            "6" _SP_VK_NAME_KEY_SUFFIX_,
            "7" _SP_VK_NAME_KEY_SUFFIX_,
            "8" _SP_VK_NAME_KEY_SUFFIX_,
            "9" _SP_VK_NAME_KEY_SUFFIX_,
            _SP_VK_NAME_UNDEFINED_,
            _SP_VK_NAME_UNDEFINED_,
            _SP_VK_NAME_UNDEFINED_,
            _SP_VK_NAME_UNDEFINED_,
            _SP_VK_NAME_UNDEFINED_,
            _SP_VK_NAME_UNDEFINED_,
            _SP_VK_NAME_UNDEFINED_,
            "A" _SP_VK_NAME_KEY_SUFFIX_,
            "B" _SP_VK_NAME_KEY_SUFFIX_,
            "C" _SP_VK_NAME_KEY_SUFFIX_,
            "D" _SP_VK_NAME_KEY_SUFFIX_,
            "E" _SP_VK_NAME_KEY_SUFFIX_,
            "F" _SP_VK_NAME_KEY_SUFFIX_,
            "G" _SP_VK_NAME_KEY_SUFFIX_,
            "H" _SP_VK_NAME_KEY_SUFFIX_,
            "I" _SP_VK_NAME_KEY_SUFFIX_,
            "J" _SP_VK_NAME_KEY_SUFFIX_,
            "K" _SP_VK_NAME_KEY_SUFFIX_,
            "L" _SP_VK_NAME_KEY_SUFFIX_,
            "M" _SP_VK_NAME_KEY_SUFFIX_,
            "N" _SP_VK_NAME_KEY_SUFFIX_,
            "O" _SP_VK_NAME_KEY_SUFFIX_,
            "P" _SP_VK_NAME_KEY_SUFFIX_,
            "Q" _SP_VK_NAME_KEY_SUFFIX_,
            "R" _SP_VK_NAME_KEY_SUFFIX_,
            "S" _SP_VK_NAME_KEY_SUFFIX_,
            "T" _SP_VK_NAME_KEY_SUFFIX_,
            "U" _SP_VK_NAME_KEY_SUFFIX_,
            "V" _SP_VK_NAME_KEY_SUFFIX_,
            "W" _SP_VK_NAME_KEY_SUFFIX_,
            "X" _SP_VK_NAME_KEY_SUFFIX_,
            "Y" _SP_VK_NAME_KEY_SUFFIX_,
            "Z" _SP_VK_NAME_KEY_SUFFIX_,
            "Left Windows" _SP_VK_NAME_KEY_SUFFIX_,
            "Right Windows" _SP_VK_NAME_KEY_SUFFIX_,
            "Applications" _SP_VK_NAME_KEY_SUFFIX_,
            _SP_VK_NAME_RESERVED_,
            "Sleep",
            _SP_VK_NUMPAD_PREFIX_ "0",
            _SP_VK_NUMPAD_PREFIX_ "1",
            _SP_VK_NUMPAD_PREFIX_ "2",
            _SP_VK_NUMPAD_PREFIX_ "3",
            _SP_VK_NUMPAD_PREFIX_ "4",
            _SP_VK_NUMPAD_PREFIX_ "5",
            _SP_VK_NUMPAD_PREFIX_ "6",
            _SP_VK_NUMPAD_PREFIX_ "7",
            _SP_VK_NUMPAD_PREFIX_ "8",
            _SP_VK_NUMPAD_PREFIX_ "9",
            _SP_VK_NUMPAD_PREFIX_ "Multiply",
            _SP_VK_NUMPAD_PREFIX_ "Add",
            _SP_VK_NAME_SEPARATOR__,
            _SP_VK_NUMPAD_PREFIX_ "Subtract",
            _SP_VK_NUMPAD_PREFIX_ "Decimal",
            _SP_VK_NUMPAD_PREFIX_ "Divide",
            "F1",
            "F2",
            "F3",
            "F4",
            "F5",
            "F6",
            "F7",
            "F8",
            "F9",
            "F10",
            "F11",
            "F12",
            "F13",
            "F14",
            "F15",
            "F16",
            "F17",
            "F18",
            "F19",
            "F20",
            "F21",
            "F22",
            "F23",
            "F24",
            _SP_VK_NAME_UNASSIGNED_,
            _SP_VK_NAME_UNASSIGNED_,
            _SP_VK_NAME_UNASSIGNED_,
            _SP_VK_NAME_UNASSIGNED_,
            _SP_VK_NAME_UNASSIGNED_,
            _SP_VK_NAME_UNASSIGNED_,
            _SP_VK_NAME_UNASSIGNED_,
            _SP_VK_NAME_UNASSIGNED_,
            "Num lock",
            "Scroll lock",
            _SP_VK_NAME_OEM_SPECIFIC_0x92_,
            _SP_VK_NAME_OEM_SPECIFIC_0x93_,
            _SP_VK_NAME_OEM_SPECIFIC_0x94_,
            _SP_VK_NAME_OEM_SPECIFIC_0x95_,
            _SP_VK_NAME_OEM_SPECIFIC_0x96_,
            _SP_VK_NAME_UNASSIGNED_,
            _SP_VK_NAME_UNASSIGNED_,
            _SP_VK_NAME_UNASSIGNED_,
            _SP_VK_NAME_UNASSIGNED_,
            _SP_VK_NAME_UNASSIGNED_,
            _SP_VK_NAME_UNASSIGNED_,
            _SP_VK_NAME_UNASSIGNED_,
            _SP_VK_NAME_UNASSIGNED_,
            _SP_VK_NAME_UNASSIGNED_,
            "Left shift",
            "Right shift",
            "Left ctrl",
            "Right ctrl",
            "Left alt",
            "Right alt",
            "Browser back",
            "Browser forward",
            "Browser refresh",
            "Browser stop",
            "Browser search",
            "Browser favorites",
            "Browser start/home",
            "Mute volume",
            "Volume down",
            "Volume up",
            "Next track",
            "Previous track",
            "Stop media",
            "Play/pause media",
            "Start mail",
            "Select media",
            "Start application 1",
            "Start application 2",
            _SP_VK_NAME_RESERVED_,
            _SP_VK_NAME_RESERVED_,
            _SP_VK_NAME_OEM_1__,
            "Plus (+)",
            "Comma",
            "Minus (-)",
            "Period (.)",
            _SP_VK_NAME_OEM_2__,
            _SP_VK_NAME_OEM_3__,
            _SP_VK_NAME_RESERVED_,
            _SP_VK_NAME_RESERVED_,
            _SP_VK_NAME_RESERVED_,
            _SP_VK_NAME_RESERVED_,
            _SP_VK_NAME_RESERVED_,
            _SP_VK_NAME_RESERVED_,
            _SP_VK_NAME_RESERVED_,
            _SP_VK_NAME_RESERVED_,
            _SP_VK_NAME_RESERVED_,
            _SP_VK_NAME_RESERVED_,
            _SP_VK_NAME_RESERVED_,
            _SP_VK_NAME_RESERVED_,
            _SP_VK_NAME_RESERVED_,
            _SP_VK_NAME_RESERVED_,
            _SP_VK_NAME_RESERVED_,
            _SP_VK_NAME_RESERVED_,
            _SP_VK_NAME_RESERVED_,
            _SP_VK_NAME_RESERVED_,
            _SP_VK_NAME_RESERVED_,
            _SP_VK_NAME_RESERVED_,
            _SP_VK_NAME_RESERVED_,
            _SP_VK_NAME_RESERVED_,
            _SP_VK_NAME_UNASSIGNED_,
            _SP_VK_NAME_UNASSIGNED_,
            _SP_VK_NAME_UNASSIGNED_,
            _SP_VK_NAME_UNASSIGNED_,
            _SP_VK_NAME_OEM_4__,
            _SP_VK_NAME_OEM_5__,
            _SP_VK_NAME_OEM_6__,
            _SP_VK_NAME_OEM_7__,
            _SP_VK_NAME_OEM_8__,
            _SP_VK_NAME_RESERVED_,
            _SP_VK_NAME_OEM_SPECIFIC_0xE1_,
            _SP_VK_NAME_OEM_102__,
            _SP_VK_NAME_OEM_SPECIFIC_0xE3_,
            _SP_VK_NAME_OEM_SPECIFIC_0xE4_,
            "IME Process",
            _SP_VK_NAME_OEM_SPECIFIC_0xE6_,
            _SP_VK_NAME_VK_PACKET_,
            _SP_VK_NAME_UNASSIGNED_,
            _SP_VK_NAME_OEM_SPECIFIC_0xE9_,
            _SP_VK_NAME_OEM_SPECIFIC_0xEA_,
            _SP_VK_NAME_OEM_SPECIFIC_0xEB_,
            _SP_VK_NAME_OEM_SPECIFIC_0xEC_,
            _SP_VK_NAME_OEM_SPECIFIC_0xED_,
            _SP_VK_NAME_OEM_SPECIFIC_0xEE_,
            _SP_VK_NAME_OEM_SPECIFIC_0xEF_,
            _SP_VK_NAME_OEM_SPECIFIC_0xF0_,
            _SP_VK_NAME_OEM_SPECIFIC_0xF1_,
            _SP_VK_NAME_OEM_SPECIFIC_0xF2_,
            _SP_VK_NAME_OEM_SPECIFIC_0xF3_,
            _SP_VK_NAME_OEM_SPECIFIC_0xF4_,
            _SP_VK_NAME_OEM_SPECIFIC_0xF5_,
            "Attn" _SP_VK_NAME_KEY_SUFFIX_,
            "CrSel" _SP_VK_NAME_KEY_SUFFIX_,
            "ExSel" _SP_VK_NAME_KEY_SUFFIX_,
            "Erase EOF",
            "Play",
            "Zoom",
            _SP_VK_NAME_VK_NONAME__,
            "PA1" _SP_VK_NAME_KEY_SUFFIX_,
            "Clear",
            _SP_VK_NAME_INVALID_
        };
#endif // SP_DEFINE_VK_NAME_STRINGS_


#endif // _WIN32


} // namespace io
__SP_NAMESPACE_CLOSE // namespace sp

#endif // SP_UTILITY_IO_VK_NAME_STRINGS_H_
